@echo off
set PATH=C:\Qt\6.9.0\mingw_64\bin;C:\Qt\Tools\mingw1310_64\bin;%PATH%
cd E:\code\trae\xxmoonTest
g++ -Wl,-s -Wl,-subsystem,console -mthreads -o release/xxmoonTest.exe ^
release/tst_xxmoontest.o ^
release/test.o ^
release/docparser.o ^
release/global.o ^
release/log.o ^
release/util.o ^
release/sm.o ^
release/http.o ^
release/trans.o ^
release/sslhelper.o ^
release/qaesencryption.o ^
release/async.o ^
release/filequeue.o ^
release/future.o ^
release/script.o ^
release/sync.o ^
release/xm_format.o ^
release/mypinyin.o ^
release/sqlite_manager.o ^
release/runmain.o ^
release/basedao.o ^
release/categorydao.o ^
release/envdao.o ^
release/notedao.o ^
release/tagdao.o ^
release/tasklogdao.o ^
release/workdao.o ^
release/xmdao.o ^
release/category.o ^
release/cfg.o ^
release/note.o ^
release/tag.o ^
release/tasklog.o ^
release/work.o ^
release/xm.o ^
release/app.o ^
release/l.o ^
release/timer.o ^
release/menumanager.o ^
release/bookaction.o ^
release/xmaction.o ^
release/hserver.o ^
release/qhotkey.o ^
release/qhotkey_win.o ^
release/moc_app.o ^
release/moc_bookaction.o ^
release/moc_cfg.o ^
release/moc_http.o ^
release/moc_l.o ^
release/moc_menumanager.o ^
release/moc_qaesencryption.o ^
release/moc_qhotkey.o ^
release/moc_qhotkey_p.o ^
release/moc_runmain.o ^
release/moc_script.o ^
release/moc_sync.o ^
release/moc_timer.o ^
release/moc_xmaction.o ^
-luser32 ^
-lWs2_32 ^
-LC:\Qt\6.9.0\mingw_64\lib ^
-lQt6Widgets ^
-lQt6QuickControls2 ^
-lQt6Quick ^
-lQt6OpenGL ^
-lQt6Gui ^
-lQt6Test ^
-lQt6QmlMeta ^
-lQt6QmlModels ^
-lQt6QmlWorkerScript ^
-lQt6Qml ^
-lQt6Network ^
-lQt6Sql ^
-lQt6Core ^
-lssl ^
-lcrypto